### PR TITLE
(feat) Build git tag archive rather than full clone and tag checkout

### PR DESCRIPTION
**Pull request by leonardb**
Simply adds option to build use the archive of the git tag rather than cloning repo and checking out tag

### CODE REVIEW

**Comment by silviucpp** [comment]
@leonardb what are the benefits here ?

**Comment by leonardb** [comment]
@silviucpp Mainly a simplification, but should also be less data to sync since you don't have to sync the entire repo history

**Comment by silviucpp** [comment]
I think we should check if `wget` and `tar` exists on the machine if not to fallback to `git`.. idea is that using `rebar` you anyway have git installed but is not mandatory to have `wget` as well

**Comment by leonardb** [comment]
Adding a check would probably be a good idea. afaik, both wget and tar are
default installs on Linux dists.

**Comment by silviucpp** [comment]
@leonardb  thank you for your work I integrated into next release after I added few more safety checks.

**Pull request closed without merging**
